### ISSUE TITLE
Formal Parameters

### ISSUE THREAD

**Issue by casser** [jonathandturner/decorators#21]
General question is how to use the API for formal parameters annotation ? 

for example : 
```javascript
class Example {
  method(@metadata("key","value") param:Type):void {}
}
```
according to output from Typescript compiler 
```javascript 
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var Example = (function () {
    function Example() {
    }
    Example.prototype.method = function (param) { };
    __decorate([
        __param(0, metadata("key", "value"))
    ], Example.prototype, "method", null);
    return Example;
})();
```
decorator will be called with additional 3th parameter index 

```javascript
decorator(target, key, paramIndex);
```

which is not matching current API spec 

```javascript
function metadata(metadataKey: any, metadataValue: any) {
    return function decorator(target: Object, targetKey?: string | symbol): void {}
}
```

So in this case instead of formal parameters the method will be annotated. 

Any thoughts on this ?

**Comment by jonathandturner** [comment]
This repo is more historic.  The more up-to-date discussions are happening at https://github.com/wycats/javascript-decorators/issues
