### ISSUE TITLE
Ability to enumerate metadata on all property keys

### ISSUE THREAD

**Issue by billccn** [jonathandturner/decorators#22]
The current proposed metadata API provides no ways of enumerating all the decorated property keys. This information should be available "statically" without a fully instantiated object.

For example, say I have a decorator that sets special property descriptions stored on some properties using the `Reflect.metadata` helper during construction. At this time, no values has been assigned to the properties yet, so `Object.keys` returns nothing.

**Comment by jonathandturner** [comment]
Please file issues on the current current decorator repo: https://github.com/wycats/javascript-decorators

**Comment by zloirock** [comment]
@jonathandturner this repo does not contain anything about metadata API. Maybe makes sense add it or that mean this proposal is dead?

**Comment by jonathandturner** [comment]
For metadata, you might be referring to what's becoming "mirrors".  You can see some thoughts here: https://github.com/wycats/javascript-decorators/blob/mirrors-spike/src/mirror.d.ts

@wycats is the right person to connect up to for the current thinking.
